/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "rphatan",
            "endpoint": "https://z08v78zxa9.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "check",
            "endpoint": "https://j9t05quew4.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "test",
            "endpoint": "https://pekissf6a2.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "form_data-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "message",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
